language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_script:
  - npm run lerna:bootstrap
after_success:
  - npm run test -- --coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
