language: node_js
node_js:
  - "6"
  - "7"
  - "8"
services:
  - rabbitmq
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database fire;' -U postgres
  - psql -d fire -c 'create extension "uuid-ossp";' -U postgres
env:
  - DATABASE_URL=postgres://postgres@localhost/fire BROKER_URL=amqp://localhost
